### PR TITLE
Code cleanup

### LINKED ISSUE #1: Code clean up
This project was started using a Play Framework example and there is still a bunch of unrelated code scattered throughout the project. This should be removed and the README should be updated from the example one.

### PR DESCRIPTION
**Pull request by btkelly**
Resolves #1

### CODE REVIEW

**Comment by macklinu** [comment]
I checked out this branch, ran `activator ui`, and it looks like there is a compilation error. Are those the correct installation/setup steps for this PR?

image

**Comment by btkelly** [comment]
Hmm not sure, compiles on my machine. I might clear out mine and clone again to make sure I'm in the same state new developers will come to the project.

**Comment by btkelly** [comment]
Also, was looking at adding Travis for a Play application to make sure things compile before being merged

**Comment by btkelly** [comment]
This now also resolves #3

**Pull request merged**
